version: "3"

services:
  web:
    image: node:16
    build:
      context: .
      dockerfile: ./Dockerfile.web
    ports:
      - 3000:3000
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
  api:
    image: node:14
    build:
      context: .
      dockerfile: ./Dockerfile.api
    depends_on:
      - redis
    links:
      - redis
    ports:
      - 3002:3002

      

